; =============================================================================
; Casper (E) (GBC) - AudioArts QuickThunder GB sound bank
; source: Casper (E) (M3) (Eng-Fre-Ger) [C][!].gbc, bank $1F, $4000-$66CD
; generated by qtgen.py; rebuilds byte-exact with RGBDS 0.9.1 (see build_check.sh)
; =============================================================================

DEF QT_STEP_SIZE EQU 2
INCLUDE "QT_Macros.inc"   ; in the parent folder (rgbasm -I ..)

; ---------------------------------------------------------------- RAM
DEF wQT EQU $D000
DEF tempo1         EQU wQT + $00
DEF notelen1       EQU wQT + $01
DEF seqadr1        EQU wQT + $02
DEF transp1        EQU wQT + $04
DEF patadr1        EQU wQT + $05
DEF note1at        EQU wQT + $07
DEF note1de        EQU wQT + $08
DEF noterset1      EQU wQT + $09
DEF duty1          EQU wQT + $0A
DEF freqtim1       EQU wQT + $0B
DEF freqtabadr1    EQU wQT + $0C
DEF freqval1       EQU wQT + $0E
DEF arptim1        EQU wQT + $10
DEF arptabadr1     EQU wQT + $11
DEF combtim1       EQU wQT + $13
DEF combtabadr1    EQU wQT + $14
DEF note1          EQU wQT + $16
DEF tempo2         EQU wQT + $17
DEF notelen2       EQU wQT + $18
DEF seqadr2        EQU wQT + $19
DEF transp2        EQU wQT + $1B
DEF patadr2        EQU wQT + $1C
DEF note2at        EQU wQT + $1E
DEF note2de        EQU wQT + $1F
DEF noterset2      EQU wQT + $20
DEF duty2          EQU wQT + $21
DEF freqtim2       EQU wQT + $22
DEF freqtabadr2    EQU wQT + $23
DEF freqval2       EQU wQT + $25
DEF arptim2        EQU wQT + $27
DEF arptabadr2     EQU wQT + $28
DEF combtim2       EQU wQT + $2A
DEF combtabadr2    EQU wQT + $2B
DEF note2          EQU wQT + $2D
DEF tempo3         EQU wQT + $2E
DEF notelen3       EQU wQT + $2F
DEF seqadr3        EQU wQT + $30
DEF transp3        EQU wQT + $32
DEF patadr3        EQU wQT + $33
DEF voltim3        EQU wQT + $35
DEF voltabadr3     EQU wQT + $36
DEF volreladr3     EQU wQT + $38
DEF freqtim3       EQU wQT + $3A
DEF freqtabadr3    EQU wQT + $3B
DEF freqval3       EQU wQT + $3D
DEF arptim3        EQU wQT + $3F
DEF arptabadr3     EQU wQT + $40
DEF combtim3       EQU wQT + $42
DEF combtabadr3    EQU wQT + $43
DEF note3          EQU wQT + $45
DEF tempo4         EQU wQT + $46
DEF notelen4       EQU wQT + $47
DEF seqadr4        EQU wQT + $48
DEF transp4        EQU wQT + $4A
DEF patadr4        EQU wQT + $4B
DEF note4at        EQU wQT + $4D
DEF note4de        EQU wQT + $4E
DEF noterset4      EQU wQT + $4F
DEF noisetim4      EQU wQT + $50
DEF noisetabadr4   EQU wQT + $51
DEF noise2tim4     EQU wQT + $53
DEF noise2tabadr4  EQU wQT + $54
DEF tempoe         EQU wQT + $56
DEF notelene       EQU wQT + $57
DEF seqadre        EQU wQT + $58
DEF transpe        EQU wQT + $5A
DEF patadre        EQU wQT + $5B
DEF noteechanadr   EQU wQT + $5F
DEF effend         EQU wQT + $61
DEF songtempo      EQU wQT + $62
DEF effprio        EQU wQT + $63
DEF morphtim       EQU wQT + $64
DEF morphadr       EQU wQT + $65
DEF wavefreqlo     EQU wQT + $67
DEF wavefreqhi     EQU wQT + $68

SECTION "QuickThunder CasperE", ROMX[$4000], BANK[$1F]

INCLUDE "CasperE_Driver.inc"
INCLUDE "CasperE_Data.inc"
