#!/usr/bin/env python3
"""Stream walker for the World Cup USA '94 (GB) sound driver (bank 3)."""
import sys
ROM = open(sys.argv[1] if len(sys.argv) > 1 else 'World Cup USA \'94 (UE) (M8) [!].gb', 'rb').read()
BANK = 3
def B(a): return BANK * 0x4000 + (a - 0x4000)
def rb(a): return ROM[B(a)]
def rw(a): return ROM[B(a)] | ROM[B(a) + 1] << 8

CH_NAMES = ['CH1 (pulse+sweep)', 'CH2 (pulse)', 'CH3 (wave)', 'CH4 (noise)']
TRK_TABLES = [0x4675, 0x4687, 0x4699, 0x46AB]
NSONGS = 9
FREQ_TBL, NOISE_TBL, INS_TBL, SFX_TBL = 0x46E1, 0x47AF, 0x47DF, 0x5730
NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

def note_name(idx):
    """Freq-table index -> nearest pitch name (from the actual table value)."""
    import math
    idx &= 0x7F                       # driver does 8-bit (note+t)*2
    f = rw(FREQ_TBL + 2 * idx)
    if idx > 102: return f'past-table:${f:04X}'
    if f == 0: return 'freq0'
    hz = 131072 / (2048 - f)
    m = round(12 * math.log2(hz / 440) + 69)
    return f'{NOTE_NAMES[m % 12]}{m // 12 - 1}'

covered = {}
def mark(a, n, tag):
    for i in range(n): covered.setdefault(a + i, tag)

def walk(start, ch, sub=False, transpose=0, out=None, depth=0):
    a = start
    ind = '    ' * depth
    while True:
        b = rb(a)
        if b < 0x80:
            dur = rb(a + 1); mark(a, 2, 'trk')
            if b == 0:
                txt = f'rest       {dur}'
            elif ch == 3:
                txt = f'drum {b:2d}    {dur}'
            else:
                eff = (b + transpose) & 0x7F
                warn = f'   <- index {b + transpose} wraps to {eff}' if not 0 <= b + transpose <= 102 else ''
                txt = f'note ${b:02X} {note_name(b + transpose):>5} {dur}{warn}'
            out.append(f'{ind}  {a:04X}: {rb(a):02X} {dur:02X}          {txt}')
            a += 2; continue
        if b < 0xC0:
            mark(a, 1, 'trk')
            note = '' if ch != 3 else '   (ignored on CH4)'
            out.append(f'{ind}  {a:04X}: {b:02X}             instrument {b - 0x80}{note}')
            a += 1; continue
        if b == 0xFF:
            mark(a, 1, 'trk'); out.append(f'{ind}  {a:04X}: FF             RESTART song'); return
        if b == 0xFE:
            mark(a, 1, 'trk'); out.append(f'{ind}  {a:04X}: FE             STOP music'); return
        if b == 0xFC:
            n = rb(a + 1); mark(a, 2, 'trk')
            out.append(f'{ind}  {a:04X}: FC {n:02X}          loop_start x{n}'); a += 2; continue
        if b == 0xFD:
            mark(a, 1, 'trk'); out.append(f'{ind}  {a:04X}: FD             loop_end'); a += 1; continue
        if b == 0xF9:
            n, t, tgt = rb(a + 1), rb(a + 2), rw(a + 3); mark(a, 5, 'trk')
            ts = t - 256 if t >= 0x80 else t
            out.append(f'{ind}  {a:04X}: F9 {n:02X} {t:02X} {tgt & 255:02X} {tgt >> 8:02X} call ${tgt:04X} x{n}, transpose {ts:+d}')
            if depth < 2:
                walk(tgt, ch, True, ts if ch != 3 else 0, out, depth + 1)
            a += 5; continue
        if b == 0xF8:
            mark(a, 1, 'trk'); out.append(f'{ind}  {a:04X}: F8             return/repeat')
            if not sub:
                out.append(f'{ind}        (F8 outside a pattern: jumps via the stale SubRet of the last F9;'
                           ' for Track_Silent this loops forever)')
            return
        mark(a, 1, 'trk')
        out.append(f'{ind}  {a:04X}: {b:02X}             (no-op command)')
        a += 1

def main():
    out = []
    out.append("World Cup USA '94 (GB) - sound data, bank 3. Generated by tools/wcparse.py\n")
    out.append('== Song table ==')
    for s in range(NSONGS):
        ptrs = [rw(t + 2 * s) for t in TRK_TABLES]
        nr = rw(0x46BD + 2 * s); n52 = rw(0x46CF + 2 * s)
        out.append(f'song {s}: CH1 ${ptrs[0]:04X}  CH2 ${ptrs[1]:04X}  CH3 ${ptrs[2]:04X}  CH4 ${ptrs[3]:04X}   NR50 ${nr & 255:02X} NR51 ${nr >> 8:02X} NR52 ${n52 & 255:02X} (unused ${n52 >> 8:02X})')
    for t in TRK_TABLES + [0x46BD, 0x46CF]: mark(t, 18, 'tbl')
    mark(FREQ_TBL, 206, 'tbl'); mark(NOISE_TBL, 48, 'tbl'); mark(INS_TBL, 128, 'tbl')
    out.append('\n== Instruments (table $47DF, selected by stream bytes $80-$BF) ==')
    ptrs = sorted(set(rw(INS_TBL + 2 * i) for i in range(64)) - {0})
    for i in range(64):
        p = rw(INS_TBL + 2 * i)
        if not p: continue
        n = rb(p)
        wave = i >= 32
        if wave:
            wav = ROM[B(p + 1):B(p + 17)].hex(' ').upper()
            vib = [rb(p + 0x11 + k) for k in range(n)]
            size = 0x11 + n
            out.append(f'ins {i:2d} (${0x80 + i:02X}) @${p:04X} WAVE  len={n} wave=[{wav}] pitchdelta={[v - 256 if v > 127 else v for v in vib]}')
        else:
            vib = [rb(p + 7 + k) for k in range(n)]
            size = 7 + n
            out.append(f'ins {i:2d} (${0x80 + i:02X}) @${p:04X} PULSE len={n} sfxfreq=${rw(p + 1):04X} +3=${rb(p + 3):02X} NR10=${rb(p + 4):02X} NR11=${rb(p + 5):02X} NR12=${rb(p + 6):02X} pitchdelta={[v - 256 if v > 127 else v for v in vib]}')
        mark(p, size, 'ins')
    nxt = {a: b for a, b in zip(ptrs, ptrs[1:] + [0x495D])}
    for p in ptrs:
        end = p + (0x11 + rb(p) if p >= 0x48F0 else 7 + rb(p))
        if end < nxt[p]:
            out.append(f'   note: ${end:04X}-${nxt[p] - 1:04X} after ins @${p:04X} unused: {ROM[B(end):B(nxt[p])].hex(" ").upper()}')
    out.append('\n== Noise (drum) table $47AF: 3 bytes per drum, drum n = entry n-1 ==')
    for i in range(16):
        a = NOISE_TBL + 3 * i; x, y, z = rb(a), rb(a + 1), rb(a + 2)
        out.append(f'drum {i + 1:2d}: NR43=${x:02X} NR42=${y:02X} ctl=${z:02X} -> NR41=${z & 63:02X} NR44=${0xC0 ^ (z & 0x40):02X}')
    out.append('\n== Frequency table $46E1 (103 words; index = note + transpose) ==')
    row = []
    for i in range(103):
        row.append(f'{i:3d}:${rw(FREQ_TBL + 2 * i):03X} {note_name(i):>5}')
        if len(row) == 6: out.append('   '.join(row)); row = []
    if row: out.append('   '.join(row))
    out.append('\n== SFX table $5730 (played on CH1 by $0F53, only while music is off) ==')
    for i in range(7):
        a = SFX_TBL + 2 * i; ins, dur = rb(a), rb(a + 1)
        out.append(f'sfx {i}: ins byte ${ins:02X} (instrument {ins & 0x7F}), {dur} ticks')
    mark(SFX_TBL, 14, 'tbl')
    seen = set()
    for s in range(NSONGS):
        for c in range(4):
            p = rw(TRK_TABLES[c] + 2 * s)
            out.append(f'\n== Song {s} {CH_NAMES[c]} @ ${p:04X} ==')
            if (p, c) in seen:
                out.append('  (same stream as listed above)'); continue
            seen.add((p, c))
            walk(p, c, out=out)
    # coverage
    out.append('\n== Coverage of $4675-$57FF ==')
    a = 0x4675; gaps = []
    while a < 0x5800:
        if a not in covered:
            s = a
            while a < 0x5800 and a not in covered: a += 1
            gaps.append((s, a))
        else: a += 1
    for s, e in gaps:
        data = ROM[B(s):B(e)]
        if all(x == 0xFF for x in data): out.append(f'  ${s:04X}-${e - 1:04X}: $FF padding'); continue
        out.append(f'  ${s:04X}-${e - 1:04X} not reached: {data[:48].hex(" ").upper()}{" ..." if len(data) > 48 else ""}')
    print('\n'.join(out))

if __name__ == '__main__':
    main()
