; =============================================================================
; Carmageddon (GBC) - AudioArts QuickThunder GB sound bank
; source: Carmageddon (UE) (M4) [C][!].gbc, bank $41, $4000-$53F9
; generated by qtgen.py; rebuilds byte-exact with RGBDS 0.9.1 (see build_check.sh)
; =============================================================================

DEF QT_STEP_SIZE EQU 2
INCLUDE "QT_Macros.inc"   ; in the parent folder (rgbasm -I ..)

; ---------------------------------------------------------------- RAM
DEF wQT EQU $D800
DEF tempo1         EQU wQT + $00
DEF notelen1       EQU wQT + $01
DEF seqadr1        EQU wQT + $02
DEF transp1        EQU wQT + $04
DEF patadr1        EQU wQT + $05
DEF note1at        EQU wQT + $07
DEF note1de        EQU wQT + $08
DEF noterset1      EQU wQT + $09
DEF freqtim1       EQU wQT + $0A
DEF freqtabadr1    EQU wQT + $0B
DEF freqval1       EQU wQT + $0D
DEF arptim1        EQU wQT + $0F
DEF arptabadr1     EQU wQT + $10
DEF combtim1       EQU wQT + $12
DEF combtabadr1    EQU wQT + $13
DEF note1          EQU wQT + $15
DEF tempo2         EQU wQT + $16
DEF notelen2       EQU wQT + $17
DEF seqadr2        EQU wQT + $18
DEF transp2        EQU wQT + $1A
DEF patadr2        EQU wQT + $1B
DEF note2at        EQU wQT + $1D
DEF note2de        EQU wQT + $1E
DEF noterset2      EQU wQT + $1F
DEF freqtim2       EQU wQT + $20
DEF freqtabadr2    EQU wQT + $21
DEF freqval2       EQU wQT + $23
DEF arptim2        EQU wQT + $25
DEF arptabadr2     EQU wQT + $26
DEF combtim2       EQU wQT + $28
DEF combtabadr2    EQU wQT + $29
DEF note2          EQU wQT + $2B
DEF tempo4         EQU wQT + $2C
DEF notelen4       EQU wQT + $2D
DEF seqadr4        EQU wQT + $2E
DEF transp4        EQU wQT + $30
DEF patadr4        EQU wQT + $31
DEF note4at        EQU wQT + $33
DEF note4de        EQU wQT + $34
DEF noterset4      EQU wQT + $35
DEF noisetim4      EQU wQT + $36
DEF noisetabadr4   EQU wQT + $37
DEF noise2tim4     EQU wQT + $39
DEF noise2tabadr4  EQU wQT + $3A
DEF tempoe         EQU wQT + $3C
DEF notelene       EQU wQT + $3D
DEF seqadre        EQU wQT + $3E
DEF transpe        EQU wQT + $40
DEF patadre        EQU wQT + $41
DEF noteechanadr   EQU wQT + $45
DEF effend         EQU wQT + $47

SECTION "QuickThunder Carmageddon", ROMX[$4000], BANK[$41]

INCLUDE "Carmageddon_Driver.inc"
INCLUDE "Carmageddon_Data.inc"
