C = {
 'SoundJumpTable': ['Sound jump table: the game only calls these five entries.'],
 'Music_Play': ['Start song A. A >= $80 stops the music (all channel flags cleared,',
                'APU_STATUS = $E0).'],
 'Music_Stop': ['Stop: clear all channel flags, APU_STATUS = $E0.'],
 'Music_LoadSong': ['Load the track pointers and the duration table pointer of song A,',
                    'reset timers/transpose/loops, enable the channels (flags = 3).'],
 'Music_Update': ['Called once per frame: run every music channel.'],
 'Music_UpdateAll': ['Run the four music channels.'],
 'Music_UpdateChannel': ['Y = channel, X = channel*4 (APU register offset).',
                         'mChanFlags bit 0 = track running, bit 1 = channel owns the APU',
                         '(cleared while a sound effect uses the channel).'],
 'Music_TickNote': ['Count down the note; read a new event when it reaches 0.'],
 'Music_ReadEvent': ['Read the next event. Bit 7 of byte 0 becomes bit 4 of the instrument.'],
 'Music_Note': ['Note: add the transpose, look up the period (unless a sound effect',
                'owns the channel).'],
 'Music_NoteSetInstrument': ['Note length from the duration table, advance 2 bytes, then load',
                             'the instrument (bit 4 from byte 0, bits 0-3 from byte 1).'],
 'Music_InstNoVolEnv': ['Instrument flags >= 2: no volume envelope.'],
 'Music_InstVolEnv': ['Instrument flags 0/1: start the volume envelope.'],
 'Music_VolEnvTick': ['Volume envelope: (volume, frames) pairs, $80 = stop.'],
 'Music_PitchEnvTick': ['Pitch envelope: (delta, frames) pairs added to the low period byte,',
                        '$80 lo hi = jump.'],
 'Music_ArpEnvTick': ['Arpeggio envelope: (note offset, frames) pairs, $80 lo hi = jump.'],
 'Music_Output': ['Write the registers that changed, if this channel owns the APU.'],
 'WriteChannelRegs': ['Write the shadow registers to the APU, Y = register offset.',
                      'mRegDirty bit 0 = reg3, bit 1 = reg2, bit 2 = reg0.'],
 'Music_Command': ['Command byte $60+: jump through CmdHandlerLo/Hi.'],
 'Cmd_Rest': ['$60 CMD_REST len: volume 0 (if reg0 bit 4, constant volume, is set), wait.'],
 'Cmd_End': ['$61 CMD_END: stop the track and silence the channel.'],
 'Cmd_Call': ['$62 CMD_CALL pattern, transpose, count'],
 'Cmd_Return': ['$63 CMD_RETURN: go back to the CMD_CALL; repeat it while the count',
                'is not 0, otherwise continue after it with transpose 0.'],
 'Cmd_ReadNextNow': ['Timer = 1 and run the channel again so the next event is read in',
                     'the same frame.'],
 'Cmd_Jump': ['$64 CMD_JUMP .word address'],
 'Cmd_DmcEnd': ['$65 CMD_DMC_END: stop the DMC track.'],
 'Cmd_DmcRest': ['$66 CMD_DMC_REST len'],
 'Cmd_SetDurTable': ['$65 CMD_DURTABLE .word table (pointer shared by all channels).'],
 'AdvanceTrackPtr': ['Track pointer += Y + 1.'],
 'SilenceChannel': ['Volume 0, period 0, mark all registers dirty.'],
 'Dmc_UpdateChannel': ['DMC track (channel 4).'],
 'Dmc_ReadEvent': ['Stop the current sample, then read the next DMC event.'],
 'Dmc_Note': ['Rate from byte 0, sample number and length from byte 1.'],
 'Dmc_AdvancePtr': ['DMC track pointer += Y + 1.'],
 'Dmc_Silence': ['Clear the DMC registers and disable the DMC.'],
 'Dmc_Output': ['Write the DMC registers if the music owns the DMC.'],
 'Dmc_WriteRegs': ['Write DMC_FREQ, DMC_START, DMC_LEN and APU_STATUS.'],
 'Sfx_Init': ['Clear all sound effect state.'],
 'Sfx_Play': ['A = priority, X = effect number. Effects with a lower priority than',
              'the one playing on the same channel are ignored.'],
 'Sfx_PlayDmc': ['DMC effect: take the DMC away from the music and start the sample.'],
 'Sfx_SetPtr': ['Effect pointer = zPtr + Y + 1.'],
 'Sfx_Update': ['Called once per frame: run every sound effect channel.'],
 'Sfx_UpdateChannel': ['X = channel.'],
 'Sfx_Stop': ['Effect finished: give the channel back to the music.'],
}
RAMC = {
 'zPtr': 'pointer: track / instrument / envelope / effect data',
 'zDurTab': 'pointer: current duration table',
 'zChan': 'current channel number', 'zRegOfs': 'current channel * 4 (APU register offset)',
 'zTemp': 'scratch',
 'mTrkPtrLo': 'track pointer low, per channel', 'mTrkPtrHi': 'track pointer high, per channel',
 'mDurTabLo': 'duration table pointer (global)', 'mDurTabHi': '',
 'mNoteTimer': 'frames left of the current note', 'mDmcTimer': 'frames left of the DMC event',
 'mVolEnvTimer': 'volume envelope', 'mVolEnvHi': '', 'mVolEnvLo': '',
 'mPitchEnvTimer': 'pitch envelope', 'mPitchEnvHi': '', 'mPitchEnvLo': '',
 'mArpEnvTimer': 'arpeggio envelope', 'mArpEnvHi': '', 'mArpEnvLo': '',
 'mInstTemp': 'instrument number / flags while loading',
 'mTranspose': 'transpose added to notes (CMD_CALL)',
 'mRetLo': 'CMD_CALL return address', 'mRetHi': '',
 'mLoopCount': 'CMD_CALL repeat count', 'mLoopActive': 'nonzero while a CMD_CALL repeats',
 'mChanFlags': 'bit 0 = track running, bit 1 = owns the APU (no effect)',
 'mDmcFlags': 'mChanFlags for the DMC track',
 'mRegDirty': 'bit 0 = reg3, bit 1 = reg2, bit 2 = reg0 need writing',
 'mDmcDirty': 'DMC write pending',
 'mNote': 'current note (after transpose)',
 'mReg3': 'shadow of register 3 (period high, length)', 'mReg2': 'shadow of register 2 (period low)',
 'mReg0': 'shadow of register 0 (duty, volume)',
 'mDmcFreq': 'shadow DMC_FREQ', 'mDmcRaw': '(cleared, never written to the APU)',
 'mDmcStart': 'shadow DMC_START', 'mDmcLen': 'shadow DMC_LEN',
 'mApuStatus': 'shadow APU_STATUS', 'mCmdVector': 'command handler address (JMP indirect)',
 'sPtrHi': 'effect pointer high, per channel (0 = none)', 'sPtrLo': 'effect pointer low',
 'mChanFlagsSave': 'mChanFlags restored when an effect ends',
 'mDmcFlagsSave': 'mDmcFlags restored when a DMC effect ends',
 'sDmcActive': 'nonzero while a DMC effect plays',
 'sTimer': 'frames until the next effect step', 'sSpeed': 'effect speed / step delay',
 'sId': 'effect number (for restart)', 'sNewPriority': 'priority passed to Sfx_Play',
 'sPriority': 'priority of the effect on each channel', 'sDmcPriority': 'priority of the DMC effect',
 'mTempo': 'tempo (added to mTempoAcc each frame)', 'mTempoAcc': 'tempo accumulator',
}
