C = {
 'SoundJumpTable': ['Duck Tales 2: two entry points, both called from the NMI handler.',
                    '$8000 Sound_Update (requests, music tracks, register output),',
                    '$8003 Sound_UpdateSfx (sound effect tracks only).'],
 'Sound_UpdateSfx': ['Run the two sound effect channels (4 = square 2, 5 = noise).'],
 'Sound_Update': ['Once per frame. Handle a new request in zSoundReq (bit 7 clear),',
                  'run the tracks, write the APU, then enable the channels that',
                  'Sound_Start set up this frame (zChanNew).'],
 'Sound_RunChannels': ['Y = number of channels, zChan = first channel. For every active',
                       'channel: read the track, run the drum macro (channel 3), then the',
                       'volume envelope.'],
 'Env_Update': ['Volume envelope of channel X. mEnv bit 7 = off (volume forced to 0).',
                'Segments are 3 bytes: frames, delta low, delta high. The 16-bit delta is',
                'added to mVol:mVolFrac every frame; the volume is the high nibble of mVol.',
                '$FE lo hi = set mVolFrac/mVol, $FF = end (volume 0, envelope off).'],
 'Env_SetValue': ['$FE lo hi: set the volume directly and keep reading.'],
 'Env_NewSegment': ['frames, delta low, delta high'],
 'Env_Step': ['Add the delta, count down the segment.'],
 'Sound_Output': ['Write the APU registers. Music channels 0-3 run only when not paused,',
                  'and square 2 / noise are skipped while a sound effect uses them',
                  '(OutputSkipMask). Then the active sound effect channels 4 and 5.'],
 'Output_Channel': ['Jump through OutputTable for channel X.'],
 'WriteVolume': ['Y = APU register offset. Volume = (mVol >> 4) - mVolAtten - zMasterAtten,',
                 'at least 0. Triangle: linear counter = volume * 4 with the control bit',
                 'set (0 = silent). Others: volume | duty | $30 (constant volume, halt).'],
 'WritePeriod': ['Sweep register when the period or sweep changed; period (stored x2)',
                 'shifted right once, high bits OR $F8 (length counter load).'],
 'Out_Sq2Drum': ["Square 2 played by the noise channel's drum macro (mSq2DrumOn): uses",
                 "channel 3's volume, attenuation and duty. All three registers are",
                 'written every frame.'],
 'Sound_Fade': ['Fade out: every 4 frames zMasterAtten + 1, until 16.',
                'BUG: when no fade-out is running the BEQ goes to the RTS, so the',
                'fade-in code after it (Sound_FadeInUnused) can never run.'],
 'Sound_FadeInUnused': ['Fade in: every 4 frames zMasterAtten - 1, until 0. Unreachable.'],
 'Sound_Request': ['A = zSoundReq. Mark it done (bit 7). $00 = Sound_Init, $01-$78 =',
                   'Sound_Start, $79-$7F = RequestTable.'],
 'Req_Resume': ['$79: resume the music channels.'],
 'Req_Pause': ['$7A: pause the music channels (sound effects keep running) and', 'silence them.'],
 'Req_7B': ['$7B: does nothing in this version.'],
 'Req_7C': ['$7C: does nothing in this version.'],
 'Req_FadeOut': ['$7B: start a fade-out.'],
 'Req_FadeIn': ['$7C: start a fade-in (never runs, see Sound_Fade).'],
 'Req_StopMusic': ['$7D: stop the music (reset channels 0-3).'],
 'Req_StopSfx': ['$7E: stop the sound effects (reset channels 4-5).'],
 'ResetChannels': ['Reset Y channels starting at X.'],
 'Sound_Init': ['$00 / $7F: silence the APU, clear $0700-$07FC and reset the channels.'],
 'Chan_Reset': ['Reset channel X: empty stack, track = SilentTrack, envelope off.'],
 'Sound_Start': ['Start sound A ($01-$78). Header byte: bits 0-3 = music channels 0-3,',
                 'bits 4-5 = sound effect channels 4-5, followed by one track pointer',
                 'per set bit. Music also clears pause/fade, the drum flags and resets',
                 "mDrumMap. The header byte is OR'ed into zChanActive at the end of",
                 'Sound_Update.'],
 'Track_Update': ['Count down the note; read the track when it reaches 0.'],
 'Track_Read': ['Commands ($D0-$FF) run through CmdTable with TrackLoopRet pushed, so',
                'reading continues until a note or rest.'],
 'Track_Note': ['Note/rest byte: high nibble = note (0-11) or $C = rest, low nibble =',
                'length - 1. Length = (n + 1) * mSpeed (mSpeed 0 = x1).'],
 'Track_NoteOn': ['Note: unless tied, restart the envelope. Channel 3: start drum',
                  'macro mDrumMap[note]. Channel 5: noise period = (note - transposes) & 15.',
                  'Others: PeriodTable[octave + note + transposes] + mDetune.'],
 'Track_SavePtr': ['Clear the tie flag and store the track pointer.'],
 'Cmd_Octave0': ['$D0-$D6: octave 0-6.'],
 'Cmd_OctaveUp': ['$D7: octave + 1.'],
 'Cmd_OctaveDown': ['$D8: octave - 1.'],
 'Cmd_Transpose': ['$D9 n: transpose = n.'],
 'Cmd_TransposeAdd': ['$DA n: second transpose += n.'],
 'Cmd_Detune': ['$DB n: signed value added to the period.'],
 'Cmd_Speed': ['$E0 n: note length multiplier.'],
 'Cmd_Duty': ['$E1 n: duty = n & 3.'],
 'Cmd_Envelope': ['$E2 n: volume envelope n; it starts with the next note.'],
 'Cmd_NopE3': ['$E3 n: argument read and ignored.'],
 'Cmd_NopE4': ['$E4 n: argument read and ignored.'],
 'Cmd_NopE5': ['$E5 n: argument read and ignored.'],
 'Cmd_Tie': ['$E8: the next note does not restart the envelope or the period.',
             '(zTie is shared by all channels.)'],
 'Cmd_Volume': ['$E9 n: volume attenuation = n.'],
 'Cmd_VolumeAdd': ['$EA n: volume attenuation += n.'],
 'Cmd_Sweep': ['$EB n: sweep register = n.'],
 'Cmd_SweepOff': ['$EC: sweep register = $08 (off).'],
 'Cmd_DrumSwap': ['$ED xy: swap mDrumMap[x] and mDrumMap[y].'],
 'Cmd_Loop': ['$F0 n: push the loop start and the count n.'],
 'Cmd_LoopEnd': ['$F1: count - 1; jump back while not 0, else drop the loop.'],
 'Cmd_Call': ['$F2 .word sub: push the return address, go to sub.'],
 'Cmd_Return': ['$F3: pop the return address.'],
 'Cmd_Jump': ['$F8 .word addr'],
 'Cmd_End': ['$FF: stop the channel. Drops TrackLoopRet so it returns straight to', 'Sound_RunChannels.'],
 'Track_ReadByte': ['A = next track byte.'],
 'Stack_PushPtr': ['Per-channel stack (16 bytes each in mStack): push the track pointer.'],
 'Stack_Push': ['Push A.'],
 'Stack_PopPtr': ['Pop the track pointer.'],
 'Stack_Pop': ['Pop A.'],
 'Drum_Start': ['Channel 3 note: drum macro pointer = DrumTable[mDrumMap[note]].'],
 'Drum_Update': ['Channel 3, every frame while its envelope is on: run the drum macro',
                 'until a step that ends the frame.'],
 'Drum_Step': ['$00-$1F noise period (value >> 1), ends the frame',
               '$40-$4F lo square 2 tone (period = ((n & 15) << 8 | lo) >> 1), ends the frame',
               '$80-$BF envelope n & $3F,  $E0-$FE duty n & 3,  others / $FF stop.'],
 'Drum_Stop': ['End: noise period 0, keep writing the noise volume; the pointer is',
               'not saved, so the macro stays on this byte.'],
}
RAMC = {
 'zSoundReq': 'sound request from the game; bit 7 = done',
 'zChanActive': 'bit n = channel n running',
 'zChanNew': "channels started this frame (OR'ed in after the update)",
 'zTemp': 'scratch / jump vector',
 'zTrkPtr': 'pointer: track / envelope / drum / header data',
 'zChan': 'current channel',
 'zFadeIn': 'fade-in request flag',
 'zFadeOut': 'fade-out request flag',
 'zFadeTimer': 'fade frame counter',
 'zMasterAtten': "subtracted from every channel's volume",
 'zPaused': 'nonzero = music channels paused',
 'zTie': 'set by CMD_TIE for the next note (shared)',
 'mStackPtr': 'per channel: index into mStack',
 'mStack': 'loop/call stack, 16 bytes per channel',
 'mTrkPtrLo': 'track pointer, per channel (6 channels)',
 'mSpeed': 'note length multiplier (CMD_SPEED)',
 'mOctave': 'octave * 12',
 'mTranspose': 'CMD_TRANSPOSE',
 'mTransposeAdd': 'CMD_TRANSPOSE_ADD',
 'mNoteTimer': 'frames left of the current note',
 'mDuty': 'duty in bits 6-7',
 'mVolAtten': 'CMD_VOLUME attenuation',
 'mEnv': 'envelope number; bit 7 = off',
 'mEnvTimer': 'frames left of the envelope segment',
 'mEnvPos': 'offset into the envelope',
 'mVolFrac': 'volume, fraction',
 'mVol': 'volume, high nibble = APU volume',
 'mEnvDeltaLo': 'envelope delta per frame',
 'mPeriodLo': 'period x 2',
 'mPeriodDirty': 'nonzero = write the period',
 'mSweep': 'sweep register value',
 'mSweepDirty': 'nonzero = write the sweep register',
 'mDetune': 'signed period offset',
 'mDrumPtrLo': 'drum macro pointer (channel 3)',
 'mSq2DrumLo': 'square 2 drum tone period x 2',
 'mSq2DrumOn': 'square 2 plays the drum tone this frame',
 'mNoiseOn': 'noise registers written this frame',
 'mDrumMap': 'note -> drum number (13 entries, CMD_DRUM_SWAP)',
}
